import Foundation

struct ExportService: Sendable {

    func generateMarkdown(crashes: [CrashLog], report: AnalysisReport) -> String {
        var md = ""

        let deviceName = report.deviceModels.max(by: { $0.value < $1.value })?.key ?? "Unknown Device"
        md += "# iCrashDiag Report — \(deviceName)\n\n"

        md += "## Summary\n"
        md += "- **Device**: \(deviceName)\n"
        if let os = report.osVersions.max(by: { $0.value < $1.value })?.key {
            md += "- **iOS**: \(os)\n"
        }
        if let dr = report.dateRange {
            let fmt = DateFormatter()
            fmt.dateStyle = .medium
            md += "- **Period**: \(fmt.string(from: dr.start)) — \(fmt.string(from: dr.end))\n"
        }
        md += "- **Total crashes**: \(report.totalCrashes)"
        let cats = report.categoryBreakdown.sorted { $0.value > $1.value }
        if !cats.isEmpty {
            md += " (" + cats.map { "\($0.value) \($0.key)" }.joined(separator: ", ") + ")"
        }
        md += "\n"
        let verdict = report.overallVerdict
        md += "- **Verdict**: \(verdict.isHardware ? "HARDWARE ISSUE" : "SOFTWARE / NORMAL") — \(verdict.confidence)% confidence\n\n"

        if let diag = report.dominantDiagnosis, let top = report.topPatterns.first {
            md += "## Primary Diagnosis\n"
            md += "**\(diag.title)**\n\n"
            md += "\(top.count)/\(report.totalCrashes) crashes — \(diag.component)\n\n"

            md += "### Probabilities\n"
            for p in diag.probabilities {
                md += "- \(p.percent)% — \(p.cause)\n"
            }
            md += "\n"

            md += "### Recommended Repair\n"
            for step in diag.repairSteps {
                md += "\(step)\n"
            }
            md += "\n"

            md += "### Test Procedure\n"
            for test in diag.testProcedure {
                md += "- \(test)\n"
            }
            md += "\n"
        }

        if !report.crashesPerDay.isEmpty {
            md += "## Timeline\n"
            md += "| Date | Crashes |\n|------|--------|\n"
            for day in report.crashesPerDay.keys.sorted() {
                md += "| \(day) | \(report.crashesPerDay[day]!) |\n"
            }
            md += "\n"
        }

        if !report.topPatterns.isEmpty {
            md += "## All Patterns Detected\n"
            md += "| Pattern | Count | Severity | Component |\n|---------|-------|----------|----------|\n"
            for p in report.topPatterns {
                md += "| \(p.title) | \(p.count) | \(p.severity.label) | \(p.component) |\n"
            }
            md += "\n"
        }

        if !report.sensorFrequency.isEmpty {
            md += "## Missing Sensors\n"
            for (sensor, count) in report.sensorFrequency.sorted(by: { $0.value > $1.value }) {
                md += "- **\(sensor)**: \(count) occurrences\n"
            }
            md += "\n"
        }

        md += "---\nGenerated by iCrashDiag v1.0\n"
        return md
    }

    func generateJSON(crashes: [CrashLog], report: AnalysisReport) throws -> Data {
        let export = ExportPayload(generatedAt: Date(), appVersion: "1.0", report: report, crashes: crashes)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(export)
    }
}

struct ExportPayload: Codable, Sendable {
    let generatedAt: Date
    let appVersion: String
    let report: AnalysisReport
    let crashes: [CrashLog]
}
